# Generated by Django 5.1.1 on 2024-10-21 08:12

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_field",
                    models.FileField(upload_to=pathlib.PurePosixPath("files/%Y/%m/%d")),
                ),
            ],
        ),
    ]
