# Generated by Django 5.1.1 on 2024-10-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageFileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_field", models.ImageField(upload_to="images/")),
                ("file_field", models.FileField(upload_to="files/")),
            ],
        ),
    ]
